version: '3'

services:
  app:
    command: "_build/dev/rel/tweetrelay/bin/tweetrelay foreground"
    image: telegram-bot-relayer
    build:
      context: .
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
    env_file: .env
