version: '3'

services:
  app:
    command: "mix run --no-halt"
    image: telegram-bot-relayer
    build:
      context: .
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
    env_file: .env
